// Shared service content — single source of truth for the /services hub page
// AND the dedicated /services/[slug] pages. Server-safe (no 'use client').

export interface Feat { t: string; d: string; }

export interface ServiceDetail {
  num: string; slug: string; name: string; h2: string; kw: string;
  hue: number; vein: number; intro: string; body: string[]; feat: Feat[];
}

export const SERVICE_DETAIL: ServiceDetail[] = [
  { num:'01', slug:'marble-polishing-dubai', name:'Marble Polishing Dubai', h2:'Premium Marble Polishing in Dubai & UAE', kw:'marble polishing dubai · marble floor polishing', hue:32, vein:0.22,
    intro:'Over time, heavy foot traffic and desert sand cause marble to lose its luster. Our multi-stage diamond marble polishing Dubai process restores a high-gloss, premium reflective finish to the floors, walls and stairs of luxury villas and commercial buildings.',
    body:['MarblePro is the best marble polishing company in Dubai for Italian Carrara, Botticino, Crema Marfil and locally-sourced natural stone. Our certified technicians grind, hone and polish with successive diamond pads from 50 to 3000 grit — then lock the result in with Italian diamond crystallization for a finish that lasts for years.','Whether you need affordable marble floor polishing for an apartment or full marble polishing and crystallization for a villa, we provide a free on-site inspection and a transparent fixed-price quote.'],
    feat:[{t:'Diamond grinding 50–3000 grit',d:'Lippage flattened, scratches erased, gloss meter reads 85+ GU.'},{t:'Italian crystallization seal',d:'Mirror finish chemically bonded into the stone, not just waxed on top.'},{t:'Dust-free wet process',d:"We never leave your villa or office covered in marble dust."},{t:'Same-day completion',d:'Most living-area floors completed in 8–14 hours of on-site work.'}]},
  { num:'02', slug:'marble-floor-restoration', name:'Marble Floor Restoration Services', h2:'Marble Floor Restoration Services Dubai', kw:'floor restoration services · marble floor restoration services', hue:28, vein:0.20,
    intro:"Cracked, etched, deep-scratched or completely yellowed marble? Our marble floor restoration services bring even the most neglected stone back to showroom condition — without ripping it out.",
    body:['Emergency residential marble floor restoration services Dubai is one of our most-requested treatments. We perform color-matched epoxy crack filling, joint leveling, deep scratch removal and acid-etch reversal — followed by full diamond polishing and crystallization.','Our floor restoration services are designed for the long haul: properly restored marble holds its shine for years with minimal maintenance, saving you the cost of full replacement.'],
    feat:[{t:'Color-matched epoxy crack filling',d:'Cracks and chips become invisible after re-polishing.'},{t:'Lippage & joint leveling',d:'We grind down uneven tiles for a perfectly flat plane.'},{t:'Acid & etch reversal',d:'Removes citrus, wine and cleaning-product damage.'},{t:'Re-polish & crystallize',d:'The final finish matches new — backed by a written guarantee.'}]},
  { num:'03', slug:'marble-countertop-polishing', name:'Countertop Polishing', h2:'Premium Marble Countertop Polishing Dubai', kw:'countertop polishing · kitchen top polishing', hue:38, vein:0.18,
    intro:'Kitchen counters and bathroom vanities face constant exposure to oils, acids, water marks and heat. We provide specialised countertop polishing and food-safe sealing to protect your investment.',
    body:['Premium marble countertop polishing Dubai is delivered with low-profile machinery that fits around your fitted cabinetry — no need to dismantle anything. Edges, splashbacks and undermount cut-outs are hand-polished separately for a flawless seam.','Our countertop polishing service is also available for marble, granite and quartz vanity tops, kitchen islands and bar counters.'],
    feat:[{t:'Edge & splash-back hand polish',d:"Where machines can't reach, our technicians work by hand."},{t:'Food-safe sealer',d:'Hydrophobic, FDA-approved — safe for direct food contact.'},{t:'Burn & ring removal',d:'Hot pan and glass-ring marks lifted and re-polished.'},{t:'Half-day turnaround',d:'Typical kitchen counter done in 4–6 hours.'}]},
  { num:'04', slug:'terrazzo-polishing-dubai', name:'Terrazzo Polishing Dubai', h2:'Terrazzo Floor Polishing Dubai — Vintage & Modern', kw:'terrazzo polishing dubai · terrazzo floor polishing dubai', hue:45, vein:0.18,
    intro:'Terrazzo is back in style across UAE architecture — and old terrazzo can be restored to a finish more beautiful than the day it was poured. We specialise in terrazzo polishing in Dubai for heritage buildings, modern villas and commercial lobbies.',
    body:['Our terrazzo floor polishing Dubai process uses fine diamond pads to smoothly level out cracks and expose the beautiful, sparkling marble and glass aggregate beneath. Aggregate colours come back vivid, and the cement matrix gets a deep, even sheen.','Whether you\'re asking for terrazzo polishing Dubai price for a 50 m² lobby or a 2,000 m² heritage hall, we provide an upfront fixed quote with no surprises.'],
    feat:[{t:'Aggregate revealed sharply',d:'Successive grits expose marble and glass chips at perfect plane.'},{t:'Cement matrix sealed',d:'Prevents future yellowing and porosity in the binder.'},{t:'Commercial-scale machinery',d:'Heavy diamond grinders make short work of 1,000+ m² jobs.'},{t:'Heritage-safe technique',d:'We assess original mix before polishing — no irreversible removal.'}]},
  { num:'05', slug:'granite-polishing', name:'Granite Polishing', h2:'Commercial Granite Polishing Services Dubai', kw:'granite polishing · floor polishing dubai', hue:20, vein:0.30,
    intro:"Renowned for its hardness, granite needs professional-grade machinery and high-grade industrial diamond discs to polish to a brilliant, glass-like reflection. MarblePro delivers slip-safe granite gloss for villas, hotels and retail floors.",
    body:["Granite polishing is technically harder than marble polishing — that's why generic floor polishing companies often skip it. We use specialised heavy-weight machinery to grind down uneven tiles (lippage) and polish granite to a brilliant, mirror-like finish.","For commercial granite polishing services Dubai — hotels, malls, premium retail — we schedule overnight and weekend work to ensure zero downtime for your business."],
    feat:[{t:'Heavy industrial diamond discs',d:"Required for granite's high silica content — generic pads simply skid."},{t:'Weather-proof sealing',d:'Granite outdoors? We seal against UV and moisture penetration.'},{t:'Slip-resistant finish',d:'Polished granite is slip-safe with our textured crystallizer.'},{t:'Annual maintenance plans',d:'Quarterly buffering keeps commercial granite at peak gloss.'}]},
  { num:'06', slug:'quartz-polishing', name:'Quartz Polishing', h2:'Premium Quartz Polishing & Stain Protection — Abu Dhabi & Dubai', kw:'quartz polishing and stain protection Abu Dhabi · Dubai', hue:50, vein:0.15,
    intro:'Engineered quartz is one of the most popular surfaces in modern UAE kitchens — but it does scratch, dull and absorb stains over time. Our specialised quartz polishing buffs out light abrasions and restores the factory-slick sheen.',
    body:['Quartz polishing is different from marble or granite polishing — quartz contains resin binders that need precise, low-heat technique. The wrong tool can melt or burn the surface permanently.','We also offer quartz polishing and stain protection Abu Dhabi for new installations: a hydrophobic resin sealer that prevents wine, oil and curry from penetrating during the first year of use.'],
    feat:[{t:'Low-heat resin-safe technique',d:"Specific to engineered stone — won't melt the binder."},{t:'Factory-slick sheen restored',d:'Light abrasions and dull spots completely erased.'},{t:'Stain-block resin sealer',d:'Optional add-on — repels oil, wine, juice for 12+ months.'},{t:'No etching from foods',d:'Quartz already acid-resistant, our finish keeps it that way.'}]},
  { num:'07', slug:'corian-countertop-polishing', name:'Corian Countertop Polishing', h2:'Professional Corian Countertop Polishing & Scratch Repair Dubai', kw:'corian countertop polishing and scratch repair Dubai', hue:42, vein:0.10,
    intro:'Corian and other solid-surface materials are repairable in ways stone is not — burns, scratches and even small holes can be invisibly fixed. Our hand-polished Corian countertop polishing and scratch repair service makes worn Corian look completely brand new.',
    body:['Corian countertop polishing and scratch repair Dubai is a craft, not a mass-produced service. Each Corian surface is sanded by hand through fine grits, then finished to your preferred sheen — matte, satin or full gloss.','We also repair Corian sinks, seam-rejoining, burn marks and chips on the original integrated installations.'],
    feat:[{t:'Hand-sand to fine grit',d:'Deep scratches and burns sanded out by hand — no machine marks.'},{t:'Matte / satin / gloss choice',d:'You pick the final finish. Each looks completely brand new.'},{t:'Seam repair & rejoin',d:'Lifted or yellowed seams re-bonded and re-polished invisibly.'},{t:'Sink & integrated repair',d:'Burns, chips, hairline cracks fixed on Corian integrated sinks.'}]},
  { num:'08', slug:'yellow-stain-removing', name:'Yellow Stain Removing', h2:'Professional Yellow Stain Removing for Natural Stone UAE', kw:'yellow stain removing Dubai · professional stone stain removal UAE', hue:48, vein:0.16,
    intro:'Yellow stains on marble are caused by iron oxidation, organic seepage, or improper cleaning chemicals — and they go deep. Our chemical poultice treatments target yellow stain removing from deep within the stone pores without damaging the surface.',
    body:['Yellow stain removing is one of our most-requested specialty services. We diagnose the cause first — rust, oil, urine, citrus, wax — then apply a stain-specific poultice that draws the pigment out over 24–48 hours.','How to remove yellow stains from marble floor Dubai is not a DIY job; aggressive bleach or acid only sets the stain deeper. Our process is professional, repeatable, and guaranteed.'],
    feat:[{t:'Stain type diagnosis',d:'Iron, organic, oil, biological — each needs a different poultice.'},{t:'Drawn out, not bleached',d:'Pigment is physically pulled from the pores — no chemical hiding.'},{t:'No surface damage',d:"We re-polish after treatment so you'd never know it was there."},{t:'24–48 hour treatment cycle',d:'Poultice applied, left to draw, removed, repeated if needed.'}]},
  { num:'09', slug:'kitchen-top-polishing', name:'Kitchen Top Polishing', h2:'Kitchen Top Polishing & Sealing Services UAE', kw:'kitchen top polishing and sealing services UAE · Dubai', hue:40, vein:0.18,
    intro:'Your kitchen counter is the centerpiece of your home — and the most punished surface in it. Kitchen top polishing and sealing services UAE delivers daily-use-grade protection that actually lasts.',
    body:['We offer kitchen top polishing for marble, granite, quartz, Corian, terrazzo and engineered stone tops. Each material gets a tailored polishing technique plus a food-safe sealant suited to its porosity.','Best kitchen top polishing company near me? We service all of Dubai, Abu Dhabi and Sharjah with same-week appointments — kitchen tops done in half a day, ready for use that night.'],
    feat:[{t:'Oil & water repellent',d:'Hydrophobic sealer rated for direct food prep contact.'},{t:'Hot-pan & ring removal',d:'Burn marks and glass rings polished out invisibly.'},{t:'Edge & cut-out polish',d:'Sink and hob cut-outs treated with the same precision as the surface.'},{t:'Half-day completion',d:'Cook on it the same evening. No fumes, no residue.'}]},
  { num:'10', slug:'crystallization-sealing', name:'Crystallization & Sealing', h2:'Italian Diamond Crystallization & Sealing — Dubai & UAE', kw:'Italian marble polishing and crystallization Dubai · floor sealing UAE', hue:36, vein:0.20,
    intro:"After polishing, the right sealant is what makes the finish last 5 years instead of 5 months. We apply true Italian diamond crystallization plus an impregnating breathable sealer to protect against future spills.",
    body:["Italian marble polishing and crystallization Dubai is the gold-standard finish for premium villas and luxury hotels. The chemistry creates a microscopic, hardened shield on top of the stone — highly mirror-reflective, slip-resistant and durable against heavy foot traffic.","We don't use cheap wax coatings that wear off in weeks. Real crystallization is a chemical bond, not a coating."],
    feat:[{t:'Italian crystallization compound',d:'Real chemical bond — not a wax or acrylic film.'},{t:'Impregnating breathable sealer',d:'Stops liquid penetration without trapping stone moisture.'},{t:'Slip-resistance rated',d:'Surprisingly grippy underfoot despite the mirror finish.'},{t:'Multi-year shine',d:'Professionally crystallized floors hold their gloss for years.'}]},
  { num:'11', slug:'travertine-polishing-dubai', name:'Travertine Polishing', h2:'Travertine Polishing Dubai — Void Filling, Honing & Crystallization', kw:'travertine polishing dubai · travertine restoration uae', hue:44, vein:0.14,
    intro:"Travertine is the UAE's most widely installed natural stone — warm cream tones, natural texture and timeless appeal. Without proper void filling and specialist sealing, travertine deteriorates quickly under foot traffic and desert sand.",
    body:['Our travertine polishing Dubai process fills every natural hole and void with colour-matched epoxy before a single diamond pad touches the surface. This prevents pitting and ensures a perfectly flat, high-gloss finish that lasts for years.','We cover travertine restoration across all 7 UAE emirates — from villa floors in Dubai Marina to hotel corridors in Abu Dhabi and heritage buildings in Sharjah.'],
    feat:[{t:'Void & pore epoxy filling',d:'Every natural hole colour-matched and filled before polishing — no pitting after.'},{t:'Lippage grinding & levelling',d:'Uneven travertine tiles ground flat with heavy diamond abrasives.'},{t:'Italian diamond crystallization',d:'Mirror finish chemically bonded into the stone — not waxed on top.'},{t:'Breathable impregnating sealer',d:'Rated for UAE heat — lets stone breathe while blocking oil and water.'}]},
  { num:'12', slug:'onyx-marble-polishing-dubai', name:'Onyx Marble Polishing', h2:'Onyx Marble Polishing Dubai — Ultra-Delicate, Ultra-Premium Stone', kw:'onyx marble polishing dubai · onyx restoration uae', hue:15, vein:0.42,
    intro:'Onyx is the rarest and most visually dramatic stone in UAE luxury interiors. Its natural translucency and bold veining are irreplaceable — but a single wrong abrasive pass can permanently destroy the surface. MarblePro handles every onyx job with surgical precision.',
    body:['We start no coarser than 400 grit on onyx — standard 50-grit entry cuts would shatter the delicate crystal structure. Each step in our ultra-fine sequence is checked against a gloss meter before advancing.','Backlit onyx feature walls and illuminated panels are restored to full transparency so light passes through evenly again — the defining characteristic of premium onyx installations.'],
    feat:[{t:'Ultra-fine 400+ grit only',d:'Coarser abrasives shatter onyx crystal structure — we never risk it.'},{t:'Translucency fully preserved',d:'The deep backlit glow that makes onyx worth every dirham is maintained.'},{t:'Etch & acid haze reversal',d:'White hazes from water and cleaning products removed without surface damage.'},{t:'UV-cured fissure stabilisation',d:'Natural fissures sealed with UV resin before polishing — invisible after.'}]},
  { num:'13', slug:'crema-marfil-polishing-dubai', name:'Crema Marfil Polishing', h2:"Crema Marfil Polishing Dubai — UAE's Most Installed Marble", kw:'crema marfil polishing dubai · crema marfil restoration uae', hue:40, vein:0.13,
    intro:"Crema Marfil is installed in more UAE homes, villas and commercial buildings than any other marble. Its warm cream background with subtle golden veining defined UAE luxury interiors for two decades — yet it dulls and etches faster than harder stones.",
    body:['Years of sand abrasion, harsh cleaning chemicals and heavy foot traffic leave Crema Marfil looking grey and lifeless. Our polishing process removes all of that — deep scratches, etch marks, acid damage, yellow discolouration — and returns the warm cream glow completely.','We cover Crema Marfil polishing across Dubai, Abu Dhabi, Sharjah and Ajman with same-week appointments for residential and commercial jobs of any scale.'],
    feat:[{t:'Deep scratch & traffic removal',d:'Years of sand and shoe abrasion removed — cream tones return fully even.'},{t:'Etch & acid reversal',d:'Citrus, cleaning product and water damage reversed completely.'},{t:'Yellow tone correction',d:'Old Crema Marfil yellowing chemically corrected and re-polished to warm cream.'},{t:'Pore sealing against future stains',d:'Breathable impregnating sealer blocks penetration without trapping moisture.'}]},
  { num:'14', slug:'calacatta-marble-polishing-dubai', name:'Calacatta Marble Polishing', h2:"Calacatta Marble Polishing Dubai — Italy's Finest Stone", kw:'calacatta marble polishing dubai · calacatta restoration uae', hue:30, vein:0.36,
    intro:"Calacatta marble commands the highest value per square metre of any natural stone in the UAE. Its pure white background and bold grey-gold veining make every slab a statement piece — and every scratch or etch immediately visible against that bright white surface.",
    body:["We use ultra-fine diamond sequences specifically designed for Calacatta's sensitive white surface — restoring pure white tone and removing etch marks without disturbing the bold vein patterns that define each unique slab.",'Bookmatched Calacatta feature walls and kitchen islands are polished as a unit so veining alignment is maintained across every joint — a detail only a specialist crew can deliver.'],
    feat:[{t:'Pure white tone restoration',d:'Yellowing, graying and dull patches fully removed — bright white returns.'},{t:'Bold vein pattern untouched',d:'Grey and gold veining preserved exactly — we work around veins, not through them.'},{t:'Anti-stain deep impregnation',d:"Premium sealer penetrates Calacatta's pores — blocks oil, wine and coffee."},{t:'Book-match & feature wall care',d:'Polished as a unit — veining alignment maintained across every panel joint.'}]},
  { num:'15', slug:'emperador-marble-polishing-dubai', name:'Emperador Marble Polishing', h2:'Emperador Marble Polishing Dubai — Rich Dark Gloss Restored', kw:'emperador marble polishing dubai · emperador restoration uae', hue:22, vein:0.28,
    intro:"Emperador is Spain's most celebrated dark marble — a rich chocolate-brown stone with striking white veining installed throughout UAE luxury bathrooms, hotel lobbies and feature staircases. Its dense structure can achieve 90+ GU gloss — among the highest readings in natural stone.",
    body:["Emperador's dark surface makes calcium deposits, white water marks and dull patches immediately visible — issues that go unnoticed on lighter stones. We remove all of these chemically before polishing, then apply a colour-enhancing sealer that deepens the chocolate tones.",'Wet areas including showers, pool surrounds and bathroom floors are treated with marine-grade sealers rated for permanent moisture exposure — essential in the UAE climate.'],
    feat:[{t:'Calcium & water mark removal',d:'Hard-water deposits removed chemically — bright white marks on dark stone disappear.'},{t:'Chocolate tone revival',d:'Dull, grey-toned Emperador restored to original rich dark brown depth.'},{t:'90+ GU gloss achievable',d:"Emperador's dense structure responds exceptionally to diamond polishing — highest gloss of any stone."},{t:'Marine-grade wet area sealing',d:'Bathroom & pool installations sealed against permanent moisture exposure.'}]},
];

// Real MarblePro project photos, optimised to WebP. Filenames are the service
// slug (keyword-rich for image SEO). Served locally from /public/images/services.
export const SVC_DETAIL_IMGS: Record<string, string> = {
  'travertine-polishing-dubai':       '/images/services/travertine-polishing-dubai.jpg',
  'onyx-marble-polishing-dubai':      '/images/services/onyx-marble-polishing-dubai.webp',
  'crema-marfil-polishing-dubai':     '/images/projects/polished-marble-floor-dubai-3.webp',
  'calacatta-marble-polishing-dubai': '/images/services/calacatta-marble-polishing-dubai.webp',
  'emperador-marble-polishing-dubai': '/images/services/emperador-marble-polishing-dubai.webp',
  'marble-polishing-dubai':           '/images/projects/polished-marble-floor-dubai-1.webp',
  'marble-floor-restoration':         '/images/projects/polished-marble-floor-dubai-6.webp',
  'marble-countertop-polishing':      '/images/services/marble-countertop-polishing.webp',
  'terrazzo-polishing-dubai':         '/images/services/terrazzo-polishing-dubai.webp',
  'granite-polishing':                '/images/services/granite-polishing.webp',
  'quartz-polishing':                 '/images/services/quartz-polishing.webp',
  'corian-countertop-polishing':      '/images/services/corian-countertop-polishing.webp',
  'yellow-stain-removing':            '/images/services/yellow-stain-removing.webp',
  'kitchen-top-polishing':            '/images/services/kitchen-top-polishing.webp',
  'crystallization-sealing':          '/images/projects/polished-marble-floor-dubai-10.webp',
};

// SEO alt text per service — descriptive + keyword + brand/location.
// Strip any "Dubai"/"UAE" already in the name so the alt doesn't repeat them.
export function serviceImgAlt(s: ServiceDetail): string {
  const label = s.name.replace(/\s*(Dubai|UAE)\s*/gi, ' ').replace(/\s+/g, ' ').trim();
  return `${label} in Dubai & UAE — professional ${label.toLowerCase()} result by MarblePro`;
}

export function getServiceDetail(slug: string): ServiceDetail | undefined {
  return SERVICE_DETAIL.find((s) => s.slug === slug);
}
